version: "3.9"

# =========
# NETWORKS
# =========
networks:
  services:
  databases:
    internal: true

# =========
# VOLUMES
# =========
volumes:
  postgres_data:
    name: postgres_data
    driver: local
  mealie_data:
    name: mealie_data
    driver: local
  grocy_data:
    name: grocy_data
    driver: local
  actualbudget_data:
    name: actualbudget_data
    driver: local
  homebox_data:
    name: homebox_data
    driver: local
  manyfold_data:
    name: manyfold_data
    driver: local
  manyfold_config:
    name: manyfold_config
    driver: local
  redis_data:
    name: redis_data
    driver: local

# =========
# SECRETS
# =========
secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt

# =========
# SERVICES
# =========
services:
  # --- Datastores (shared) ---
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Docker
      POSTGRES_PASSWORD: run/secrets/postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: [databases]

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks: [databases]

  # --- Apps ---
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.4.0
    container_name: mealie
    restart: always
    ports:
      - "9925:80"
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/Anchorage
      #BASE_URL: https://mealie.yourdomain.com
      # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: Docker
      POSTGRES_PASSWORD: run/secrets/postgres_password
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
    volumes:
      - mealie_data:/app/data
    networks: [services, databases]

  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    restart: always
    ports:
      - "9283:9283"
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: America/Detroit
    volumes:
      - grocy_data:/config
    network: [services]

  actualbudget:
    image: actualbudget/actual-server:latest
    container_name: actualbudget
    restart: always
    ports:
      - "5006:5006"
    volumes:
      - actualbudget_data:/data
    network: [services]

  homebox:
    image: ghcr.io/hay-kot/homebox:latest
    container_name: homebox
    restart: always
    ports:
      - 3100:7754
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=10
    volumes:
      - homebox_data:/data
    network: [services]

  manyfold:
    image: lscr.io/linuxserver/manyfold:latest
    container_name: manyfold
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DATABASE_URL= postgresql://Docker:run/secrets/postgres_password@postgres:5432/manyfold
      - REDIS_URL=redis
      - SECRET_KEY_BASE=
    volumes:
      - manyfold_config:/config
      - manyfold_data:/libraries #optional
    depends_on:
      - postgres
    network: [services, databases]

