version: "3.9"

# --- NETWORKS ---
networks:
  services:
  databases:

# --- VOLUMES ---
volumes:
  manyfold_data:
    name: manyfold_data
    driver: local
  manyfold_config:
    name: manyfold_config
    driver: local
  
# --- SERVICES ---
services:
  manyfold:
    image: lscr.io/linuxserver/manyfold:latest
    container_name: manyfold
    restart: unless-stopped #always
    ports:
      - 3000:3000
    environment:
       - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DATABASE_URL= postgresql://Docker:run/secrets/postgres_password@postgres:5432/manyfold
      #- REDIS_URL=redis
      #- SECRET_KEY_BASE=
    volumes:
      - manyfold_config:/config
      - manyfold_data:/libraries
    depends_on:
      - postgres
    network: [services, databases]
