version: "3.9"

# --- NETWORKS ---
networks:
  services:

# --- VOLUMES ---
volumes:
  nextcloud:
    name: nextcould_main
    driver: local
  apps:
    name: nextcould_apps
    driver: local
  config:
    name: nextcould_config
    driver: local
  data:
    name: nextcould_data
    driver: local

# --- SECRETS ---
secrets:
  nextcloud_admin:
    file: ./secrets/nextcloud_admin.txt
  nextcloud_password:
    file: ./secrets/nextcloud_password.txt
  
# --- SERVICES ---
services:
  nextcloud:
    image: nextcloud:apache
    container_name: nextcloud
    restart: unless-stopped #always
    ports:
      - 8100:80
    environment:
      - POSTGRES_HOST: postgres
      - POSTGRES_PASSWORD: run/secrets/postgres_password
      - POSTGRES_DB: nextcloud
      - POSTGRES_USER: Docker
      - NEXTCLOUD_ADMIN_USER: run/secrets/
      - NEXTCLOUD_ADMIN_PASSWORD: run/secrets/
    volumes:
      nextcloud:/var/www/html
      apps:/var/www/html/custom_apps
      config:/var/www/html/config
      data:/var/www/html/data
      #theme:/var/www/html/themes/<YOUR_CUSTOM_THEME>
