version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - /path/to/media:/media
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - radarr_config:/config
      - /path/to/downloads:/downloads
      - /path/to/movies:/movies
    ports:
      - "7878:7878"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - sonarr_config:/config
      - /path/to/downloads:/downloads
      - /path/to/tv:/tv
    ports:
      - "8989:8989"
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - bazarr_config:/config
      - /path/to/movies:/movies
      - /path/to/tv:/tv
    ports:
      - "6767:6767"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - prowlarr_config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - qbittorrent_config:/config
      - /path/to/downloads:/downloads
    ports:
      - "8081:8080"
      - "6881:6881/udp"
    restart: unless-stopped

  tdarr:
    image: ghcr.io/haveagitgat/tdarr
    container_name: tdarr
    ports:
      - "8265:8265"
      - "8266:8266"
    volumes:
      - tdarr_config:/app/configs
      - tdarr_server:/app/server
      - tdarr_transcode:/app/transcode_cache
    restart: unless-stopped

volumes:
  jellyfin_config:
  jellyfin_cache:
  radarr_config:
  sonarr_config:
  bazarr_config:
  prowlarr_config:
  qbittorrent_config:
  tdarr_config:
  tdarr_server:
  tdarr_transcode:
