version: "3.8"

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - "51820:51820/udp"
    volumes:
      - wireguard_config:/config
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    network_mode: host
    privileged: true
    volumes:
      - tailscale_var:/var/lib
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped

  pihole:
    image: pihole/pihole
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8088:80"
    environment:
      - TZ=UTC
    volumes:
      - pihole_data:/etc/pihole
      - dnsmasq_data:/etc/dnsmasq.d
    restart: unless-stopped

  adguard:
    image: adguard/adguardhome
    container_name: adguard
    ports:
      - "3000:3000"
      - "3001:3001/tcp"
      - "3001:3001/udp"
    volumes:
      - adguard_data:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    restart: unless-stopped

  dnscrypt-proxy:
    image: jedisct1/dnscrypt-proxy
    container_name: dnscrypt-proxy
    ports:
      - "5053:5053/udp"
    volumes:
      - dnscrypt_config:/config
    restart: unless-stopped

  glances:
    image: nicolargo/glances
    container_name: glances
    ports:
      - "61208:61208"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    pid: host
    restart: unless-stopped

volumes:
  wireguard_config:
  tailscale_var:
  pihole_data:
  dnsmasq_data:
  adguard_data:
  adguard_conf:
  dnscrypt_config:
