version: "3.8"

volumes:
  npm_data:
  npm_letsencrypt:
  uptimekuma_data:
  postgres_data:
  
services:
  nginx-proxy-manager:
    image: docker.io/jc21/nginx-proxy-manager:latest
    ports:
      - "89:80"
      - "81:81"     # NPM admin UI
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  uptime-kuma:
    image: docker.io/louislam/uptime-kuma
    ports:
      - "3001:3001"
    volumes:
      - uptimekuma_data:/app/data
    restart: unless-stopped

  postgres:
    image: docker.io/postgres:14
    environment:
      - POSTGRES_PASSWORD=plausiblepass
      - POSTGRES_USER=plausible
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
